// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = 'https://jortjktkxjrspxhltdfj.supabase.co';
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvcnRqa3RreGpyc3B4aGx0ZGZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3ODkzMjUsImV4cCI6MjA3MjM2NTMyNX0.o-OFw155Mohd3pa726pzm9UTNnHoxTqMhZ9dNoi1u4w';
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || supabaseUrl;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || supabaseKey;  

          


// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});