// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibajmiysgfxotzibqtnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliYWptaXlzZ2Z4b3R6aWJxdG5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDc5NTYsImV4cCI6MjA3MDQ4Mzk1Nn0.t5oDG0FLfay6D1eDWXDWRr2h8S-nYAHlphGhi9y5Nq8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});